// Copyright (C) RenZhai.2021.All Rights Reserved.

#pragma once
#include "SimpleProtocolsDefinition.h"

//Only for high concurrency UDP
DEFINITION_SIMPLE_PROTOCOLS_FORCE(SocketAddressRequest, 1024)
DEFINITION_SIMPLE_PROTOCOLS_FORCE(SocketAddressResponse, 1025)
DEFINITION_SIMPLE_PROTOCOLS_FORCE(BindingAddressRequest, 1026)
DEFINITION_SIMPLE_PROTOCOLS_FORCE(BindingAddressResponse, 1027)

DEFINITION_SIMPLE_PROTOCOLS(Hello,1028)
DEFINITION_SIMPLE_PROTOCOLS(Challenge, 1029)
DEFINITION_SIMPLE_PROTOCOLS(Login, 1030)
DEFINITION_SIMPLE_PROTOCOLS(Welcom, 1031)
DEFINITION_SIMPLE_PROTOCOLS(Join, 1032)

DEFINITION_SIMPLE_PROTOCOLS(Debug, 1033)
DEFINITION_SIMPLE_PROTOCOLS(Failure, 1034)
DEFINITION_SIMPLE_PROTOCOLS(Upgrade, 1035)

DEFINITION_SIMPLE_PROTOCOLS(HeartBeat, 1036)
DEFINITION_SIMPLE_PROTOCOLS_FORCE(Close, 1037)

DEFINITION_SIMPLE_PROTOCOLS(HandshaketoSend, 1038)
DEFINITION_SIMPLE_PROTOCOLS(ReadytoAccept, 1039)
DEFINITION_SIMPLE_PROTOCOLS(Send, 1040)
DEFINITION_SIMPLE_PROTOCOLS(Recv, 1041)
DEFINITION_SIMPLE_PROTOCOLS(RecvComplete, 1042)

//Verify if online
DEFINITION_SIMPLE_PROTOCOLS_FORCE(PingRequest, 1043)
DEFINITION_SIMPLE_PROTOCOLS_FORCE(PingResponse, 1044)
